# Copyright (c) 2021 aasaam software development group
image: docker:stable

services:
  - docker:dind

stages:
  - build

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - docker login --username=$DOCKER_HUB_USER --password=$DOCKER_HUB_PASS
  - docker login --username=$QUAY_HUB_USER --password=$QUAY_HUB_PASS quay.io
  - docker login --username=$GITHUB_HUB_USER --password=$GITHUB_HUB_PASS docker.pkg.github.com
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
    # build
    - docker build -f Dockerfile -t aasaam/php-docker-image .
    # push
    - |
      docker push aasaam/php-docker-image
      docker image tag aasaam/php-docker-image quay.io/aasaam/php-docker-image
      docker push quay.io/aasaam/php-docker-image
      docker image tag aasaam/php-docker-image docker.pkg.github.com/aasaam/php-docker-image/php-docker-image
      docker push docker.pkg.github.com/aasaam/php-docker-image/php-docker-image
      docker image tag aasaam/php-docker-image $CI_REGISTRY/aasaam/php-docker-image:latest
      docker push $CI_REGISTRY/aasaam/php-docker-image:latest
    # remove image
    - docker rmi aasaam/php-docker-image
