# Copyright(c) 2021 aasaam software development group
version: "3"

services:
  php-docker-image:
    container_name: php-docker-image
    image: aasaam/php-docker-image
    working_dir: /app
    volumes:
      - ./app:/app
    environment:
      ASM_PUBLIC_APP_TEST: "false"
      CONFIGURE_PHP_INI_FILE_UPLOADS: "${CONFIGURE_PHP_INI_FILE_UPLOADS:-0}"
      CONFIGURE_PHP_INI_SESSION_NAME: "${CONFIGURE_PHP_INI_SESSION_NAME:-app_sid}"
      CONFIGURE_PHP_INI_POST_MAX_SIZE: "${CONFIGURE_PHP_INI_POST_MAX_SIZE:-6m}"
      CONFIGURE_PHP_INI_UPLOAD_MAX_FILESIZE: "${CONFIGURE_PHP_INI_UPLOAD_MAX_FILESIZE:-4m}"
      CONFIGURE_PHP_INI_OPCACHE_INTERNED_STRINGS_BUFFER: "${CONFIGURE_PHP_INI_OPCACHE_INTERNED_STRINGS_BUFFER:-8}"
      CONFIGURE_PHP_INI_OPCACHE_MAX_ACCELERATED_FILES: "${CONFIGURE_PHP_INI_OPCACHE_MAX_ACCELERATED_FILES:-10000}"
      CONFIGURE_PHP_INI_OPCACHE_MEMORY_CONSUMPTION: "${CONFIGURE_PHP_INI_OPCACHE_MEMORY_CONSUMPTION:-128}"
      CONFIGURE_PHP_INI_OPCACHE_REVALIDATE_FREQ: "${CONFIGURE_PHP_INI_OPCACHE_REVALIDATE_FREQ:-0}"
      CONFIGURE_PHP_INI_OPCACHE_VALIDATE_TIMESTAMPS: "${CONFIGURE_PHP_INI_OPCACHE_VALIDATE_TIMESTAMPS:-1}"
      CONFIGURE_PHP_INI_OPCACHE_MAX_WASTED_PERCENTAGE: "${CONFIGURE_PHP_INI_OPCACHE_MAX_WASTED_PERCENTAGE:-15}"
      CONFIGURE_PHP_INI_MAX_EXECUTION_TIME: "${CONFIGURE_PHP_INI_MAX_EXECUTION_TIME:-10}"
      CONFIGURE_PHP_INI_MAX_FILE_UPLOADS: "${CONFIGURE_PHP_INI_MAX_FILE_UPLOADS:-1}"
      CONFIGURE_PHP_INI_REALPATH_CACHE_SIZE: "${CONFIGURE_PHP_INI_REALPATH_CACHE_SIZE:-4096K}"
      CONFIGURE_PHP_INI_REALPATH_CACHE_TTL: "${CONFIGURE_PHP_INI_REALPATH_CACHE_TTL:-600}"
      CONFIGURE_PHP_INI_APC_SHM_SIZE: "${CONFIGURE_PHP_INI_APC_SHM_SIZE:-128M}"
      CONFIGURE_PHP_INI_APC_ENTRIES_HINT: "${CONFIGURE_PHP_INI_APC_ENTRIES_HINT:-8192}"
      CONFIGURE_PHP_FPM_MAX_CHILDREN: "${CONFIGURE_PHP_FPM_MAX_CHILDREN:-256}"
      CONFIGURE_PHP_FPM_START_SERVERS: "${CONFIGURE_PHP_FPM_START_SERVERS:-8}"
      CONFIGURE_PHP_FPM_MIN_SPARE_SERVERS: "${CONFIGURE_PHP_FPM_MIN_SPARE_SERVERS:-4}"
      CONFIGURE_PHP_FPM_MAX_SPARE_SERVERS: "${CONFIGURE_PHP_FPM_MAX_SPARE_SERVERS:-256}"

  php-docker-image-worker:
    container_name: php-docker-image-worker
    image: aasaam/php-docker-image
    working_dir: /app
    entrypoint: /entrypoint-worker.sh
    stop_signal: SIGKILL
    command: /app/worker.php
    volumes:
      - ./app:/app
    environment:
      ASM_PUBLIC_APP_TEST: "false"
      CONFIGURE_PHP_INI_FILE_UPLOADS: "${CONFIGURE_PHP_INI_FILE_UPLOADS:-0}"
      CONFIGURE_PHP_INI_SESSION_NAME: "${CONFIGURE_PHP_INI_SESSION_NAME:-app_sid}"
      CONFIGURE_PHP_INI_POST_MAX_SIZE: "${CONFIGURE_PHP_INI_POST_MAX_SIZE:-6m}"
      CONFIGURE_PHP_INI_UPLOAD_MAX_FILESIZE: "${CONFIGURE_PHP_INI_UPLOAD_MAX_FILESIZE:-4m}"
      CONFIGURE_PHP_INI_OPCACHE_INTERNED_STRINGS_BUFFER: "${CONFIGURE_PHP_INI_OPCACHE_INTERNED_STRINGS_BUFFER:-8}"
      CONFIGURE_PHP_INI_OPCACHE_MAX_ACCELERATED_FILES: "${CONFIGURE_PHP_INI_OPCACHE_MAX_ACCELERATED_FILES:-10000}"
      CONFIGURE_PHP_INI_OPCACHE_MEMORY_CONSUMPTION: "${CONFIGURE_PHP_INI_OPCACHE_MEMORY_CONSUMPTION:-128}"
      CONFIGURE_PHP_INI_OPCACHE_REVALIDATE_FREQ: "${CONFIGURE_PHP_INI_OPCACHE_REVALIDATE_FREQ:-0}"
      CONFIGURE_PHP_INI_OPCACHE_VALIDATE_TIMESTAMPS: "${CONFIGURE_PHP_INI_OPCACHE_VALIDATE_TIMESTAMPS:-1}"
      CONFIGURE_PHP_INI_OPCACHE_MAX_WASTED_PERCENTAGE: "${CONFIGURE_PHP_INI_OPCACHE_MAX_WASTED_PERCENTAGE:-15}"
      CONFIGURE_PHP_INI_MAX_EXECUTION_TIME: "${CONFIGURE_PHP_INI_MAX_EXECUTION_TIME:-10}"
      CONFIGURE_PHP_INI_MAX_FILE_UPLOADS: "${CONFIGURE_PHP_INI_MAX_FILE_UPLOADS:-1}"
      CONFIGURE_PHP_INI_REALPATH_CACHE_SIZE: "${CONFIGURE_PHP_INI_REALPATH_CACHE_SIZE:-4096K}"
      CONFIGURE_PHP_INI_REALPATH_CACHE_TTL: "${CONFIGURE_PHP_INI_REALPATH_CACHE_TTL:-600}"
      CONFIGURE_PHP_INI_APC_SHM_SIZE: "${CONFIGURE_PHP_INI_APC_SHM_SIZE:-128M}"
      CONFIGURE_PHP_INI_APC_ENTRIES_HINT: "${CONFIGURE_PHP_INI_APC_ENTRIES_HINT:-8192}"

  php-docker-image-nginx:
    container_name: php-docker-image-nginx
    depends_on:
      - php-docker-image
    image: nginx:1
    working_dir: /app
    ports:
      - 19000:80
    environment:
      # private
      CONFIGURE_NGINX_PHP_CONTAINER_NAME: ${CONFIGURE_NGINX_PHP_CONTAINER_NAME:-php-docker-image}
      CONFIGURE_NGINX_WORKER_PROCESSES: ${CONFIGURE_NGINX_WORKER_PROCESSES:-auto}
      CONFIGURE_NGINX_WORKER_RLIMIT_NOFILE: ${CONFIGURE_NGINX_WORKER_RLIMIT_NOFILE:-40960}
      CONFIGURE_NGINX_WORKER_CONNECTIONS: ${CONFIGURE_NGINX_WORKER_CONNECTIONS:-4096}
      CONFIGURE_NGINX_ERROR_LOG_LEVEL: ${CONFIGURE_NGINX_ERROR_LOG_LEVEL:-warn}
      CONFIGURE_NGINX_CLIENT_BODY_TIMEOUT: ${CONFIGURE_NGINX_CLIENT_BODY_TIMEOUT:-10}
      CONFIGURE_NGINX_CLIENT_MAX_BODY_SIZE: ${CONFIGURE_NGINX_CLIENT_MAX_BODY_SIZE:-2m}
      CONFIGURE_NGINX_DIRECTIO: ${CONFIGURE_NGINX_DIRECTIO:-2m}
      CONFIGURE_NGINX_KEEPALIVE_REQUESTS: ${CONFIGURE_NGINX_KEEPALIVE_REQUESTS:-128}
      CONFIGURE_NGINX_KEEPALIVE_TIMEOUT: ${CONFIGURE_NGINX_KEEPALIVE_TIMEOUT:-600}
      CONFIGURE_NGINX_SENDFILE_MAX_CHUNK: ${CONFIGURE_NGINX_SENDFILE_MAX_CHUNK:-1m}
      CONFIGURE_NGINX_SEND_TIMEOUT: ${CONFIGURE_NGINX_SEND_TIMEOUT:-5}
      CONFIGURE_NGINX_MAP_HASH_BUCKET_SIZE: ${CONFIGURE_NGINX_MAP_HASH_BUCKET_SIZE:-128}
      CONFIGURE_NGINX_ACCESS_LOG: ${CONFIGURE_NGINX_ACCESS_LOG:-off}
      CONFIGURE_NGINX_ERROR_LOG: ${CONFIGURE_NGINX_ERROR_LOG:-/dev/stdout}
      CONFIGURE_NGINX_FASTCGI_BUFFER_SIZE: ${CONFIGURE_NGINX_FASTCGI_BUFFER_SIZE:-128k}
      CONFIGURE_NGINX_FASTCGI_BUFFERS_NUMBER: ${CONFIGURE_NGINX_FASTCGI_BUFFERS_NUMBER:-4}
      CONFIGURE_NGINX_FASTCGI_BUFFERS_SIZE: ${CONFIGURE_NGINX_FASTCGI_BUFFERS_SIZE:-256k}
      CONFIGURE_NGINX_FASTCGI_BUSY_BUFFERS_SIZE: ${CONFIGURE_NGINX_FASTCGI_BUSY_BUFFERS_SIZE:-256k}
    volumes:
      - ./app/public:/app/public:ro
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/nginx/mime.types:/etc/nginx/mime.types:ro
      - ./config/nginx/default.conf:/etc/nginx/templates/default.conf.template:ro
