# Copyright(c) 2021 aasaam software development group
version: "3"

services:
  php-docker-image:
    container_name: php-docker-image
    image: aasaam/php-docker-image
    working_dir: /app
    volumes:
      - ./app:/app
    environment:
      ASM_PUBLIC_APP_TEST: "false"
      ASM_PHP_INI_FILE_UPLOADS: "${ASM_PHP_INI_FILE_UPLOADS:-0}"
      ASM_PHP_INI_SESSION_NAME: "${ASM_PHP_INI_SESSION_NAME:-app_sid}"
      ASM_PHP_INI_POST_MAX_SIZE: "${ASM_PHP_INI_POST_MAX_SIZE:-6m}"
      ASM_PHP_INI_UPLOAD_MAX_FILESIZE: "${ASM_PHP_INI_UPLOAD_MAX_FILESIZE:-4m}"
      ASM_PHP_INI_OPCACHE_INTERNED_STRINGS_BUFFER: "${ASM_PHP_INI_OPCACHE_INTERNED_STRINGS_BUFFER:-8}"
      ASM_PHP_INI_OPCACHE_MAX_ACCELERATED_FILES: "${ASM_PHP_INI_OPCACHE_MAX_ACCELERATED_FILES:-10000}"
      ASM_PHP_INI_OPCACHE_MEMORY_CONSUMPTION: "${ASM_PHP_INI_OPCACHE_MEMORY_CONSUMPTION:-128}"
      ASM_PHP_INI_OPCACHE_REVALIDATE_FREQ: "${ASM_PHP_INI_OPCACHE_REVALIDATE_FREQ:-0}"
      ASM_PHP_INI_OPCACHE_VALIDATE_TIMESTAMPS: "${ASM_PHP_INI_OPCACHE_VALIDATE_TIMESTAMPS:-1}"
      ASM_PHP_INI_OPCACHE_MAX_WASTED_PERCENTAGE: "${ASM_PHP_INI_OPCACHE_MAX_WASTED_PERCENTAGE:-15}"
      ASM_PHP_INI_MAX_EXECUTION_TIME: "${ASM_PHP_INI_MAX_EXECUTION_TIME:-10}"
      ASM_PHP_INI_MAX_FILE_UPLOADS: "${ASM_PHP_INI_MAX_FILE_UPLOADS:-1}"
      ASM_PHP_FPM_MAX_CHILDREN: "${ASM_PHP_FPM_MAX_CHILDREN:-5}"
      ASM_PHP_FPM_START_SERVERS: "${ASM_PHP_FPM_START_SERVERS:-2}"
      ASM_PHP_FPM_MIN_SPARE_SERVERS: "${ASM_PHP_FPM_MIN_SPARE_SERVERS:-1}"
      ASM_PHP_FPM_MAX_SPARE_SERVERS: "${ASM_PHP_FPM_MAX_SPARE_SERVERS:-3}"

  php-docker-image-worker:
    container_name: php-docker-image-worker
    image: aasaam/php-docker-image
    working_dir: /app
    entrypoint: /entrypoint-worker.sh
    stop_signal: SIGKILL
    command: /app/worker.php
    volumes:
      - ./app:/app
    environment:
      ASM_PUBLIC_APP_TEST: "false"
      ASM_PHP_INI_FILE_UPLOADS: "${ASM_PHP_INI_FILE_UPLOADS:-0}"
      ASM_PHP_INI_SESSION_NAME: "${ASM_PHP_INI_SESSION_NAME:-app_sid}"
      ASM_PHP_INI_POST_MAX_SIZE: "${ASM_PHP_INI_POST_MAX_SIZE:-6m}"
      ASM_PHP_INI_UPLOAD_MAX_FILESIZE: "${ASM_PHP_INI_UPLOAD_MAX_FILESIZE:-4m}"
      ASM_PHP_INI_OPCACHE_INTERNED_STRINGS_BUFFER: "${ASM_PHP_INI_OPCACHE_INTERNED_STRINGS_BUFFER:-8}"
      ASM_PHP_INI_OPCACHE_MAX_ACCELERATED_FILES: "${ASM_PHP_INI_OPCACHE_MAX_ACCELERATED_FILES:-10000}"
      ASM_PHP_INI_OPCACHE_MEMORY_CONSUMPTION: "${ASM_PHP_INI_OPCACHE_MEMORY_CONSUMPTION:-128}"
      ASM_PHP_INI_OPCACHE_REVALIDATE_FREQ: "${ASM_PHP_INI_OPCACHE_REVALIDATE_FREQ:-0}"
      ASM_PHP_INI_OPCACHE_VALIDATE_TIMESTAMPS: "${ASM_PHP_INI_OPCACHE_VALIDATE_TIMESTAMPS:-1}"
      ASM_PHP_INI_OPCACHE_MAX_WASTED_PERCENTAGE: "${ASM_PHP_INI_OPCACHE_MAX_WASTED_PERCENTAGE:-15}"
      ASM_PHP_INI_MAX_EXECUTION_TIME: "${ASM_PHP_INI_MAX_EXECUTION_TIME:-10}"
      ASM_PHP_INI_MAX_FILE_UPLOADS: "${ASM_PHP_INI_MAX_FILE_UPLOADS:-1}"
      ASM_PHP_FPM_MAX_CHILDREN: "${ASM_PHP_FPM_MAX_CHILDREN:-5}"
      ASM_PHP_FPM_START_SERVERS: "${ASM_PHP_FPM_START_SERVERS:-2}"
      ASM_PHP_FPM_MIN_SPARE_SERVERS: "${ASM_PHP_FPM_MIN_SPARE_SERVERS:-1}"
      ASM_PHP_FPM_MAX_SPARE_SERVERS: "${ASM_PHP_FPM_MAX_SPARE_SERVERS:-3}"

  php-docker-image-nginx:
    container_name: php-docker-image-nginx
    depends_on:
      - php-docker-image
    image: nginx:1
    working_dir: /app
    ports:
      - 19000:80
    environment:
      # private
      ASM_NGINX_PHP_CONTAINER_NAME: ${ASM_NGINX_PHP_CONTAINER_NAME:-php-docker-image}
      ASM_NGINX_WORKER_PROCESSES: ${ASM_NGINX_WORKER_PROCESSES:-2}
      ASM_NGINX_WORKER_RLIMIT_NOFILE: ${ASM_NGINX_WORKER_RLIMIT_NOFILE:-1024}
      ASM_NGINX_WORKER_CONNECTIONS: ${ASM_NGINX_WORKER_CONNECTIONS:-512}
      ASM_NGINX_ERROR_LOG_LEVEL: ${ASM_NGINX_ERROR_LOG_LEVEL:-debug}
      ASM_NGINX_CLIENT_BODY_TIMEOUT: ${ASM_NGINX_CLIENT_BODY_TIMEOUT:-10}
      ASM_NGINX_CLIENT_MAX_BODY_SIZE: ${ASM_NGINX_CLIENT_MAX_BODY_SIZE:-2m}
      ASM_NGINX_DIRECTIO: ${ASM_NGINX_DIRECTIO:-2m}
      ASM_NGINX_KEEPALIVE_REQUESTS: ${ASM_NGINX_KEEPALIVE_REQUESTS:-128}
      ASM_NGINX_KEEPALIVE_TIMEOUT: ${ASM_NGINX_KEEPALIVE_TIMEOUT:-600}
      ASM_NGINX_SENDFILE_MAX_CHUNK: ${ASM_NGINX_SENDFILE_MAX_CHUNK:-1m}
      ASM_NGINX_SEND_TIMEOUT: ${ASM_NGINX_SEND_TIMEOUT:-5}
      ASM_NGINX_MAP_HASH_BUCKET_SIZE: ${ASM_NGINX_MAP_HASH_BUCKET_SIZE:-128}
      ASM_NGINX_ACCESS_LOG: ${ASM_NGINX_ACCESS_LOG:-/dev/stdout}
      ASM_NGINX_ERROR_LOG: ${ASM_NGINX_ERROR_LOG:-/dev/stdout}
      ASM_NGINX_FASTCGI_BUFFER_SIZE: ${ASM_NGINX_FASTCGI_BUFFER_SIZE:-128k}
      ASM_NGINX_FASTCGI_BUFFERS_NUMBER: ${ASM_NGINX_FASTCGI_BUFFERS_NUMBER:-4}
      ASM_NGINX_FASTCGI_BUFFERS_SIZE: ${ASM_NGINX_FASTCGI_BUFFERS_SIZE:-256k}
      ASM_NGINX_FASTCGI_BUSY_BUFFERS_SIZE: ${ASM_NGINX_FASTCGI_BUSY_BUFFERS_SIZE:-256k}
    volumes:
      - ./app/public:/app/public:ro
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/nginx/mime.types:/etc/nginx/mime.types:ro
      - ./config/nginx/default.conf:/etc/nginx/templates/default.conf.template:ro
